### ISSUE TITLE
Tests no longer work due to version incompatabilities

### ISSUE THREAD

**Issue by MatthewFlamm** [custom-components/integration_blueprint#53]
## Version of the custom_component
0.0.0, but this is not a bug of the custom_component itself.  This is the commit I tested it on: https://github.com/custom-components/integration_blueprint/commit/8637de6b1f8720cb67ae48188a4e3563cea376ec

## Configuration

N/A

## Describe the bug
When cloning repository, creating a new virtual environment, and running tests, the tests fail.  This is due to version incompatibility between `homeassistant` and `pytest-homeassistant-custom-component`. 

```
pip install -r requirements_test.txt
pytest tests
```

## Debug log

Get a lot of errors like:

```text

File "/path/to/homeassistant/helpers/device_registry.py", line 620, in async_get
    return cast(DeviceRegistry, hass.data[DATA_REGISTRY])
KeyError: 'device_registry'

```

**Comment by MatthewFlamm** [comment]
I propose waiting for homeassistant 2021.4.0 to be released, so that we can pin the version here to a full homeassistant release.  If we pin `pytest-homeassistant-custom-component` to 0.3.0, then it will require installing a beta homeassistant release.

**Comment by ludeeus** [comment]
Just bump it to 0.0.3, the flow here is to be in line with dev anyway
