### ISSUE TITLE
Unable to add multiple sensors from same domain

### ISSUE THREAD

**Issue by golles** [custom-components/integration_blueprint#62]
## Configuration

```yaml

Add your logs here.

```

## Describe the bug
I tried adding multiple sensors in my integration, but only the last one was created. I did see something in the logs about unique id's (stupid enough I didn't save the log, and it was last weekend when I worked on it and fixed this.

I'm creating multiple sensors in a loop:
https://github.com/golles/ha-knmi/blob/main/custom_components/knmi/sensor.py#L12

In entity class I changed this:
```python
    def unique_id(self):
        """Return a unique ID to use for this entity."""
        return self.config_entry.entry_id
```
to:
```python
    def unique_id(self):
        """Return a unique ID to use for this entity."""
        return f"{self.config_entry.entry_id}-{self.name}"
```
and this seems to work, no complaints about the unique id and I get all the sensors that I expected. I do have to admit I don't have much python experience so I'm not sure if this is THE solution or maybe I did break something else, but still wanted to share my discovery to help make this project better.

## Debug log

```text

Add your logs here.

```

**Comment by ludeeus** [comment]
The unique ID needs to be unique pr. entity in the same domain.
https://developers.home-assistant.io/docs/entity_registry_index/#unique-id
