### ISSUE TITLE
Unable to open the dev container in VS Code

### ISSUE THREAD

**Issue by dummylabs** [custom-components/integration_blueprint#71]
## Version of the custom_component
Latest from the GitHub.

## Configuration

```yaml

Default configuration from integration blueprint

```

## Describe the bug
Unable to open the dev container in VS Code (version 1.65). Steps to reproduce:
1. git clone https://github.com/custom-components/integration_blueprint
2. Open integration_blueprint as folder in VS Code
3. Reopen project in container as VS Code suggests
4. The following error occurs:

```
[2511 ms] Start: Run in container: /bin/sh -c container install
Collecting git+git://github.com/home-assistant/home-assistant.git@dev
  Cloning git://github.com/home-assistant/home-assistant.git (to revision dev) to /tmp/pip-req-build-djrom8q7
ERROR: Command errored out with exit status 128: git clone -q git://github.com/home-assistant/home-assistant.git /tmp/pip-req-build-djrom8q7 Check the logs for full command output.
WARNING: You are using pip version 20.2.4; however, version 22.0.4 is available.
You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
[7885 ms] postCreateCommand failed with exit code 1. Skipping any further user-provided commands.
```

If the same clone command issued from the terminal the following error occurs:

```
git clone -q git://github.com/home-assistant/home-assistant.git
fatal: remote error:
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```

# Workaround
Run terminal in the container (Terminal->New Terminal):
1. `nano /usr/share/container/upgrade`
2. replace `python3 -m pip install --upgrade git+git://github.com/home-assistant/home-assistant.git@dev` with `python3 -m pip install --upgrade git+https://github.com/home-assistant/home-assistant.git@dev`, save changes
4. run `container install`

**Comment by dummylabs** [comment]
I've found a workaround to make container working. 
Run terminal in the container (Terminal->New Terminal):
1. `nano /usr/share/container/upgrade`
2. replace `python3 -m pip install --upgrade git+git://github.com/home-assistant/home-assistant.git@dev` to `python3 -m pip install --upgrade git+https://github.com/home-assistant/home-assistant.git@dev`, save changes
4. run `container install`

**Comment by ehendrix23** [comment]
Had same issue. Your solution resolved it.

**Comment by Limych** [comment]
@ehendrix23, @dummylabs, Just fix this line in `devcontainer.json`: https://github.com/Limych/ha-blueprint/blob/47bd29ffbc8c76f09617db56141403549c6bd0a0/.devcontainer/devcontainer.json#L3

Or you can use my version of this repository, which I've update regularly: https://github.com/Limych/ha-blueprint

**Comment by mattrayner** [comment]
I have opened a PR that fixes this by changing the devcontainer image to the new supported URL. The existing URL is out if date.
