### ISSUE TITLE
Cannot install the integration

### ISSUE THREAD

**Issue by usingapc** [custom-components/integration_blueprint#80]
I can't install the Integration.  I have tried manually adding the files to the custom components director like the read me describes.  I have also tried adding the custom repository via HACS.  In both cases when I go to add the Integration I see a Jellyfish Lighting integration but immediately get an error pop up:

Error
Config flow could not be loaded: {"message":"Invalid handler specified"}

OK button.

**Comment by usingapc** [comment]
wrong repo

**Comment by oliverbutler** [comment]
@usingapc What was the right repo, same issue here
