### ISSUE TITLE
RFC: Usage state?

### ISSUE THREAD

**Issue by ludeeus** [custom-components/integration_blueprint#83]
Hi 👋,

Looking at the state of this (past commits, open issues/PRs), it's clear that this is not really maintained.

I started this repository way back (https://github.com/custom-components/integration_blueprint/commit/f686660196b52221283c1edf7223b9a245716828) with the goal of having a simple starting point for CC authors to start with.
This repo is falling a lot out of sync with core, and even starting it will now have issues. It's clear that somewhere it fell out of my scope of my thoughts.

For me, it's the tests and linters/rules that made me reluctant to continue updating it.
I made an attempt 1,5 years ago <https://github.com/custom-components/integration_blueprint/pull/60> but eventually gave up on it. It went so far that Im currently unsubscribed from this repository.

I have this weekend gone over a lot of old stuff and updated/deprecated them, once of which is <https://github.com/ludeeus/container> which among other things generates the devcontainer that is refrenced in this repo.

If there are not any strong opinions against it I want to do the folowing to it:
- Transfer the repository to https://github.com/ludeeus
- Strip it for all tests/linters
- Reduce code to absolute minimum
- Update to current standards
- Add back a subset of usefull linters used by core (maybe [ruff](https://github.com/charliermarsh/ruff)?)
- Tests will not be added back as test are not really possible to do in a generic way, and the main purpose of this is to be generic.

Tagging @oncleben31, @MatthewFlamm, @raman325, @jcgoette  for input, as you have committed to this repo in the past.

**Comment by raman325** [comment]
I'm ok with this approach. As the maintainer, you have to do what makes it easiest for you to maintain going forward and I definitely do not pay enough attention to it to commit to being a maintainer

**Comment by raman325** [comment]
I wonder if there's a more full featured alternative that this repo can link to? I know @oncleben31 was doing a lot of work on his cookiecutter project, if that's still maintained it is a great reference to have someone be able to see example tests

**Comment by ludeeus** [comment]
Looks like <https://github.com/oncleben31> has not committed anything anywhere since December 2021.
I'll carry out the plan outlined above, thanks for your inputs @raman325 👍

**Comment by Shulyaka** [comment]
This repo has been a good example on how to add tests to a custom integration. It has helped me a lot. May be at least leave a link to https://github.com/ludeeus/integration_blueprint/tree/59fac81f40cd4596ddde3fc7e69de530c8c2ae57/tests in README.md for a starting point?
